---
title: "Datasheet for Datasets"
author: "Antoine Blanchard"
date: '2022-05-29'
output: pdf_document
---
| **Motivations pour la création du jeu de données** | **Composition du jeu de données** | **Processus de collecte des données** | **Pré-traitement des données** | **Diffusion du jeu de données** | **Maintenance du jeu de données** | **Considérations légales et éthiques** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| • Pourquoi le jeu de données a-t-il été initialement créé ? | • Que contient le jeu de données principalement ? Les enregistrements représentent-ils principalement des documents, des personnes, des territoires, des entreprises… ? | • Comment les données ont été collectées (avec des capteurs, manuellement, par des outils informatiques…) ? | • Comment les données ont-elles nettoyées ou préparées ? | • Les données sont-elles diffusées en ligne ? Selon quelles modalités (sur un portail open data, un site web, une API…) ? | • Qui assure la maintenance du jeu de données ? Comment peut-on contacter cette personne ? Quel est le service responsable du jeu de données ? | • Si le jeu de données concerne des individus, ont-ils exprimé leur consentement de manière claire ? |
| • Quelles ont été les utilisations non prévues du jeu de données ? | • Dispose-t-on d’un schéma décrivant les variables du jeu de données ? | • Qui a assuré le processus de collecte de données (des agents, des bénévoles, des étudiants…) ? | • Les données « brutes » ont-elles été conservées ? Sont-elles diffusées ? | • Si non, les données sont-elles diffusées au cas par cas ? à la demande ? | • Est-ce que les rôles sont distincts entre la production des données, leur éditorialisation et leur diffusion ? | • Les individus ont-ils été informés sur la finalité du traitement de données ? |
| • Pour quelles autres tâches le jeu de données pourrait-il être utilisé ? | • Que contient chaque champ du jeu de données ? | • Quelle a été la période de collecte des données ? | • L’outil de pré-traitement des données est-il disponible ? | • Selon quelle licence les données sont-elles diffusées ? | • Le jeu de données sera-t-il mis à jour ? Si oui, à quelle fréquence ? | • Le jeu de données peut-il exposer de manière directe ou indirecte des individus ? |
| • Quelles sont les utilisations trompeuses du jeu de données ? | • Est-ce que le contenu du jeu de données dépend de ressources externes (ex. identifiant SIRET ou lien vers le document…) ? De quelles garanties dispose-t-on concernant la pérennité de ces ressources ? | • Les données ont-elles été collectées directement ou inférées à partir d’autres données ? |  | • Des redevances ou des restrictions sont-elles appliquées dans l’accès aux données ? | • Si les données deviennent obsolètes, comment cette information sera-t-elle communiquée ? | • Ces données sont-elles conformes au RGPD ? |
| • Qui a financé ou soutenu la création du jeu de données ? |  | • Les données ont-elles été collectées sur un échantillon ? Quelle est la population complète ? Selon quelles méthodes ? |  |  | • Est-il possible de contribuer à l’amélioration des données ? Selon quelles modalités ? | • Les données peut-elles avantager ou désavantager des groupes sociaux ? |
|  |  | • Quelles sont les erreurs connues, les limites, les sources de bruit ou de redondances associées à ces données ? |  |  |  | • Le jeu de données contient-il des informations pouvant être considérées comme inappropriées ou offensantes ? |